version: 2

sources:
  - name: powerflow #name of the source you will reference in the models
    database: powerflow #name of database
    schema: public
    tables: #name all of the tables you would reference in the models
      - name: registrations_raw
        description: Users registrations data
        columns:
          - name: user_id
            description: Unique user id
          - name: registration_time
            description: Registration_timestamp
          - name: device_id
            description: User device id
          - name: email
            description: User email
          - name: platform
            description: Users operation system or mobile platform
      - name: appsflyer_raw
        description: Users attribution data
        columns:
          - name: ATTRIBUTION_COST
            description: cost for attribution per campaign 
          - name: ATTRIBUTION_TIME
            description: attribution_timestamp
          - name: CAMPAIGN_ID
            description: id of the campaign
          - name: CHANNEL
            description: channel of campaign 
          - name: DEVICE_ID
            description: Users unique device id
      - name: google_ads
        description: Users attribution data
        columns:
          - name: DEVICE_ID
            description: Users unique device id 
          - name: ATTRIBUTION_TIME
            description: attribution_timestamp
          - name: CAMPAIGN
            description: id of the campaign
      - name: transactions
        description: Users transaction data
        columns:
          - name: USER_ID
            description: Users user id 
          - name: TRANSACTION_ID
            description: unique transaction id
          - name: TOTAL_VALUE
            description: total value of unique transaction
          - name: TRANSACTION_TIME
            description: attribution_timestamp
      - name: campaign_costs
        description: attributon cost only for google campaigns
        columns:
          - name: COST
            description: cost per campaign 
          - name: CAMPAIGN_ID
            description: unique campaign id
         
models:
  - name: stg_registrations_clean
    description: this model filters out users who haven't completed registration 
    columns: 
      - name: user_id
        tests: #tests that would be run on the column
          - unique

  - name: int_marketing_attribution 
    description: this model combines the aligned colums of the tables google ads and applyers
                  data on attribution and costs
    columns: 
      - name: device_id
        tests:
          - unique
          - not_null
      - name: attribution_cost
        tests:
          - not_null

  - name: int_ltv
    description: this model calculates the users lifetime, 
                  the daily rev and the cumulated daily rev for a certain lifetime
    columns: 
      - name: reg_date
        tests:
            - not_null
      - name: transaction_date
        tests:
           - not_null
  - name: marts_roi
    description: this model calculates the roi in % for each user
    columns: 
      - name: attribution_cost
        tests:
            - not_null
      - name: roi_pct
        tests:
           - not_null
          
