version: 2

sources:
  - name: powerflow #name of the source you will reference in the models
    database: powerflow #name of database
    schema: public
    tables: #name all of the tables you would reference in the models
      - name: registrations_raw
        description: Users registrations data
        columns:
          - name: user_id
            description: Unique user id
          - name: registration_time
            description: Registration_timestamp
          - name: device_id
            description: User device id
          - name: email
            description: User email
          - name: platform
            description: Users operation system or mobile platform
      - name: appsflyer_raw
        description: Users attribution data
        columns:
          - name: ATTRIBUTION_COST
            description: cost for attribution per campaign 
          - name: ATTRIBUTION_TIME
            description: attribution_timestamp
          - name: CAMPAIGN_ID
            description: id of the campaign
          - name: CHANNEL
            description: channel of campaign 
          - name: DEVICE_ID
            description: Users unique device id
      - name: google_ads
        description: Users attribution data
        columns:
          - name: DEVICE_ID
            description: Users unique device id 
          - name: ATTRIBUTION_TIME
            description: attribution_timestamp
          - name: CAMPAIGN
            description: id of the campaign
      - name: transactions
      - name: campaign_costs
models:
  - name: stg_registrations_clean
    columns: 
      - name: user_id
        tests: #tests that would be run on the column
          - unique

  - name: int_marketing_attribution 
    columns: 
      - name: device_id
        tests:
          - unique
          - not_null
      - name: attribution_cost
        tests:
          - not_null

  - name: int_ltv
    columns: 
      - name: reg_date
        tests:
            - not_null
      - name: transaction_date
        tests:
           - not_null
  - name: marts_roi
    columns: 
      - name: attribution_cost
        tests:
            - not_null
      - name: roi_pct
        tests:
           - not_null
          
